version: '3.8'

services:
  web:
    image: ghcr.io/isikepalaku/reserseai:latest
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge