version: '3.8'

services:
  web:
    image: ghcr.io/isikepalaku/reserseai:latest
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
